tracer.property: "I AM THE DEFAULT"
#spring.datasource.driverClassName: com.mysql.jdbc.Driver
#spring.datasource.url: jdbc:mysql://localhost:3306/eagle_eye_local?useUnicode=true&characterEncoding=utf-8&useSSL=false
#spring.datasource.username: root
#spring.datasource.password: s814466057
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eagle_eye_local?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: s814466057
mybatis:
  type-aliases-package: com.echo.pojo
  mapper-locations: classpath:mybatis/mappers/**/*.xml
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
